site_name: EE5419 ROS
site_url: "https://kingbenny101.github.io/EE5419-ROS/"
site_author: "Benstin Davis"
repo_url: "https://github.com/KingBenny101/EE5419-ROS/"
repo_name: "KingBenny101/EE5419-ROS"

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Experiments: 
    - Gazebo: experiments/gazebo.md
  - About: about.md

theme:
  name: "material"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.top
    - navigation.instant
    - navigation.footer
    - navigation.expand
    - header.autohide
    - toc.follow
    - search.suggest

  plugins:
    - search
    - optimize

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KingBenny101/EE5419-ROS/
